### ISSUE TITLE
Identify gaps in business strategy - other categories?

### ISSUE THREAD

**Issue by cfe84** [mspnp/architecture-center#1330]
This is a good table, I think of a few other things to consider with why the cloud makes sense in you business strategy:
- Procurement complexity - onprem hardware is traditionally complex to purchase, and the lead time to actually receive it can be counted in weeks. In a scaling enterprise, cloud can help a lot
- Go to market and agility - advanced added-value technologies can help greatly reduce GTM times, and allow faster iterations
- Service Management Modernization - no physical provisioning means self-service is possible, and so you can increase the self-sufficiency and QoS for departments of your companies. 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 3ddb728c-056c-7699-d898-77dab53209f3
* Version Independent ID: 183f4567-8c8b-5af8-50cb-a2bd50accb06
* Content: [CAF: Getting started with the Cloud Adoption Framework - Microsoft Cloud Adoption Framework for Azure](https://docs.microsoft.com/en-us/azure/architecture/cloud-adoption/getting-started/overview)
* Content Source: [docs/cloud-adoption/getting-started/overview.md](https://github.com/mspnp/architecture-center/blob/master/docs/cloud-adoption/getting-started/overview.md)
* Service: **architecture-center**
* GitHub Login: @Petertaylor9999
* Microsoft Alias: **pnp**

**Comment by KetanChawda-MSFT** [comment]
@cfe84 Thank you for providing your feedback. I have assigned this issue to content author to further review and take a right course of action on it.

**Comment by BrianBlanchard** [comment]
Charles,

Thanks for the feedback. I agree, these are good things to consider regarding the business strategy.
Over the next few months, we will rolling out a good bit of content in CAF. As part of that rollout plan we will be adding guidance around business strategy and motives for moving to the cloud. I'd actually like to pull these topics into that stream instead of adding them to this older article.

Thanks again for the idea. Please keep them coming!
-Brian
