### ISSUE TITLE
Service bus / event hubs and event grid positioned wrong in document

### ISSUE THREAD

**Issue by ChristianWolf42** [mspnp/architecture-center#264]
In the [cloud service map](https://docs.microsoft.com/en-us/azure/architecture/aws-professional/services):
Service bus is placed at the wrong spot:
Right now it is placed in developer tools but it must be placed in enterprise integration.
It should also have an additional line:
Pub/Sub messaging for distributed systems and serveless applications
Next column: Simple Notification Service
Next column Azure Event Grid

Event Hubs needs to be additionally in analytics and big data.
Kinesis streams maps to event hubs
Kinesis firehose maps to event hubs capture

This needs to be adjusted in IoT.

**Comment by lbrader** [comment]
@ChristianWolf42 Good input - adding it to the backlog.  After AWS Re-invent conference we are planning a major refactoring of the table.   I'm leaving the PR open so we can revisit it when we refactor the table.

**Comment by bennage** [comment]
bump

**Comment by lbrader** [comment]
@ChristianWolf42  Working to update the table based on your request for IOT. Current update is [here](https://github.com/mspnp/architecture-center/blob/larry/updateAWStoAzure264/docs/aws-professional/services.md) .

Following questions - note you can S+ me:
1. Why move Service Bus out of Developer Tools to Enterprise Integration?  Reviewing the content The Service Bus seems to go well with the other developer services such as Azure Queue Storage and so on?  
2. I added the Azure Event Grid under the Service Bus since it's a message service.  
3. Updated the Event Hubs Capture in IOT.  On duplicating "Event Hubs" to be also in Analytics and Big Data - we have been working not to do any duplicates. The table will become unreadable.

**Comment by bennage** [comment]
I'm assuming that this has been resolved offline; otherwise please reopen.

**Comment by ChristianWolf42** [comment]
@lbrader and @bennage 
For your replies:
1. Service Bus is not a developer tool. It is an enterprise integration message broker. Hence that is where it belongs too. Azure storage queue is a simple task queue and both can't be compared to service bus but even that is not a dev tool.
2. Event grid is not a messaging service but a cross clout reactive programming platform so shouldn't be under service bus.
3. Event hubs is more big data and analytics than IOT.
Please send me the most recent document so we can make sure there is nothing wrong.
