### ISSUE TITLE
Azure AD App Roles Claim Type

### ISSUE THREAD

**Issue by AggieCMD** [mspnp/architecture-center#508]
The documentation states that the claim type will be "http://schemas.microsoft.com/ws/2008/06/identity/claims/role" but I see the claim come back with the type "roles". 

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 0184d69e-7219-f4f0-6583-32f79f5a76e1
* Version Independent ID: 49e5b0f0-69cb-4ab1-c8d9-62eb07778a88
* Content: [Application roles](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/app-roles)
* Content Source: [docs/multitenant-identity/app-roles.md](https://github.com/mspnp/architecture-center/blob/master/docs/multitenant-identity/app-roles.md)
* Service: **guidance**
* GitHub Login: @MikeWasson
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
I haven't looked at this stuff in awhile but I think the claim type is "schemas/.../role" but in the JWT token it's "roles". See this doc: https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-token-and-claims#idtokens

**Comment by apercova** [comment]
How can we achieve having role claim inside SAML Assertion on SSO configuration for an enterprise application?.
I configured my application as this docs stands but SAML Assertion does not have role claim.
I further considered adding a custom "AppRoles" claim mapping it to "user.assignedroles" source attribute but this source attribute is always empty so SAML Assertion is issued without "AppRoles" attribute. 
Do anybody know if any API Permissions are needed in order to make this stuff out.
Thanks ind advance.
