### ISSUE TITLE
The recommendation of the retry policy for AAD/MSI is inconsistent

### ISSUE THREAD

**Issue by bingosummer** [mspnp/architecture-center#544]
MSI is one way of using AAD. But the recommendation is inconsistent.
https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#azure-active-directory mentions 429 and 5xx.
https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/how-to-use-vm-token#retry-guidance only mentions 429.
https://github.com/Azure/azure-sdk-for-ruby/issues/1285 mentions 429, 404 and 5xx.

Will this doc include the retry guidance for MSI and recommend a consistent retry policy? For example,
1. Do AAD with service principal and AAD with MSI follow the same retry policy?
2. Do we need to retry for the status code 404 when using AAD or MSI?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 8194899c-dee2-70ac-422a-edc06e779f7c
* Version Independent ID: cafc7418-404c-5908-3037-dba7f452087b
* Content: [Retry service specific guidance](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#azure-active-directory)
* Content Source: [docs/best-practices/retry-service-specific.md](https://github.com/mspnp/architecture-center/blob/master/docs/best-practices/retry-service-specific.md)
* Service: **guidance**
* Product: **unspecified**
* GitHub Login: @dragon119
* Microsoft Alias: **pnp**

**Comment by MikeWasson** [comment]
Hi - The guidance in the [first doc](https://docs.microsoft.com/en-us/azure/architecture/best-practices/retry-service-specific#azure-active-directory) doesn't apply to MSI, only to calling Azure AD through the public HTTP endpoints. We'll update this doc to point to the MSI-specific guidance.

The second doc mentions 404 and 5xx in the section on [Error handling](https://docs.microsoft.com/en-us/azure/active-directory/managed-service-identity/how-to-use-vm-token#error-handling). But I agree that doc is a bit confusing, because the section "Retry guidance" doesn't mention those error codes. I'll open a separate issue to update that section.
