### ISSUE TITLE
Outdated link title

### ISSUE THREAD

**Issue by dcbrown16** [mspnp/architecture-center#816]
"For more information, see Placement of the Windows Server AD DS database and SYSVOL."
The article linked in this sentence (https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/introduction-to-active-directory-domain-services-ad-ds-virtualization-level-100#BKMK_PlaceDB) has no section with this title. Is this still the intended link?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 65f26361-0def-4ae9-e28a-8a8d4f97b87f
* Version Independent ID: ef55eb02-6543-88ad-4f89-5a553848bc67
* Content: [Extend Active Directory Domain Services (AD DS) to Azure](https://docs.microsoft.com/en-us/azure/architecture/reference-architectures/identity/adds-extend-domain)
* Content Source: [docs/reference-architectures/identity/adds-extend-domain.md](https://github.com/mspnp/architecture-center/blob/master/docs/reference-architectures/identity/adds-extend-domain.md)
* Service: **guidance**
* GitHub Login: @telmosampaio
* Microsoft Alias: **pnp**

**Comment by kazshi** [comment]
I found the section titled "Placement of the Windows Server AD DS database and SYSVOL" (line #1280 in source) in [Guidelines for Deploying Windows Server Active Directory on Azure Virtual Machines](https://msdn.microsoft.com/en-us/library/mt674703.aspx) - I assume the link should refer the section but I would like to make sure, please check.  Thanks.

**Comment by MikeWasson** [comment]
@dcbrown16 Yes, that looks right, thanks! I'll update the link.

**Comment by KjetilEVRY** [comment]
But the link that @kazshi referring to, and what this article links to (Guidelines for Deploying Windows Server Active Directory on Azure Virtual Machines), are from 2015(!). That's a very long time ago for Azure..... Where are the updated documentation??

**Comment by dcbrown16** [comment]
@KjetilEVRY I understand that @MicrosoftGuyJFlo is working on updates to the documentation below.
https://docs.microsoft.com/en-us/windows-server/identity/ad-ds/introduction-to-active-directory-domain-services-ad-ds-virtualization-level-100

**Comment by dcbrown16** [comment]
@KjetilEVRY yes, the lack of clear guidance on running DCs in Azure is a frequent pain point for support (where I work).
In previous MS internal investigations of the matter, I was given the impression that the docs I linked to would be updated to address DCs as VMs a little better. Looks like that is captured in feedback over there already.
https://github.com/MicrosoftDocs/windowsserverdocs/issues/2061
If you have specific requests for the doc I would take it up on that issue.

**Comment by KjetilEVRY** [comment]
Alright, that seems to be reasonable. But who is actually in charge of the documentation, the PG? I've raised several questions about this in the AzureAdvisors groups, but no response. And the last documentation is from 2015, which is kinda .... old? So much have changed in Azure since then :) And running a DC as a VM in Azure is blocker for transition large customers to Azure.

**Comment by dcbrown16** [comment]
I have never been able to identify a group that is really "in charge" of DCs on Azure. It has a ripple effect in unclear documentation for networking, Backup/ASR and so on. Hoping the new docs will help.

**Comment by MicrosoftGuyJFlo** [comment]
@dcbrown16 and @KjetilEVRY Sorry for the delay in response I was on vacation last week on a warm beach somewhere.

I own the docs for traditional AD (https://docs.microsoft.com/windows-server/identity/ad-ds/active-directory-domain-services) as well as some parts of Azure AD (https://docs.microsoft.com/azure/active-directory/authentication/index). (I am an IT Pro who has been in the industry since the early 2000s who now writes documentation) 

As mentioned I am working on a better doc for placing AD DS in Azure VMs. If you would like to send me an email (See my profile) I can send you the draft I have been working on that includes an Azure CLI script that deploys a pair of VMs in an availability set. 

In the meantime, if you have any ideas of what we could do to better address the gap I am open to ideas and collaboration.
